<a href="https://colab.research.google.com/github/Sautam05/NumPy/blob/main/numpy_final_assign_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [12]:
# Write your code here
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [15]:
# Write your code here
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [14]:
# Write your code here
import numpy as np
arr = np.array([5,10,15,20,25])
print(arr[0])
print(arr[2])
print(arr[-1])

5
15
25



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [16]:
# Write your code here
import numpy as np
arr = np.array([2,4,6,8,10,12,14,16])
print(arr[2:6])

[ 6  8 10 12]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [4]:
# Write your code here
import numpy as np
arr = np.array([5,10,15,20,25])
print(arr[[0,3,4]])

[ 5 20 25]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [7]:
# Write your code here
import numpy as np
arr = np.array([3,5,22,17,10,20,24,30])
arr > 15
print(arr[arr>15])

[22 17 20 24 30]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [1]:
# Write your code here
import numpy as np
a = np.array([10,20,30,40,50])
print(a+10)

[20 30 40 50 60]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [2]:
# Write your code here
import numpy as np
arr = np.array([3,5,23,13,43,52,7])
print(f"Sum is: {arr.sum()}")
print(f"Mean is: {arr.mean()}")
print(f"Max is: {arr.max()}")
print(f"Min is: {arr.min()}")


Sum is: 146
Mean is: 20.857142857142858
Max is: 52
Min is: 3



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [8]:
# Write your code here
import numpy as np
arr = np.array([3,2,7,20,15,9,52])
print(np.sort(arr))

[ 2  3  7  9 15 20 52]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [9]:
# Write your code here
import numpy as np
a = np.array([2,4,6])
b = np.array([8,10,12])
print(np.concatenate([a,b]))


[ 2  4  6  8 10 12]


In [11]:
A = np.array([[2,4,6],[8,10,12]])
B = np.array([[1,3,5],[7,9,11]])
print(np.vstack([A,B]))

[[ 2  4  6]
 [ 8 10 12]
 [ 1  3  5]
 [ 7  9 11]]
